version: "3"
services: 
  # Redis 설정  
  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis.conf
    command: redis-server /usr/local/etc/redis.conf
  
  # P3X Redis UI 설정
  registry:
    image: patrikx3/p3x-redis-ui:latest
    restart: always
    container_name: p3x-redis-ui
    ports:
      - "7843:7843"
    volumes:
      - ./settings:/settings