version: '2'

# https://devs0n.tistory.com/m/67

services:
  zoo1:
    platform: linux/amd64
    image: confluentinc/cp-zookeeper:6.0.13
    container_name: cluster-zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888
    restart: always


  kafka1:
    platform: linux/amd64
    image: confluentinc/cp-kafka:6.0.13
    container_name: cluster-kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zoo1
    restart: always

  kafka-ui:
    platform: linux/amd64
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "5001:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=PLAINTEXT://kafka1:19092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zoo:2181
      - KAFKA_CLUSTERS_0_READONLY=false
    depends_on:
      - zoo1
      - kafka1
    restart: always

# =================================================
#  kafka-magic:
#    image: "digitsy/kafka-magic"
#    ports:
#      - "5000:80"
#    volumes:
#      - .:/config
#    environment:
#      KMAGIC_ALLOW_TOPIC_DELETE: "true"
#      KMAGIC_ALLOW_SCHEMA_DELETE: "true"
#      KMAGIC_CONFIG_STORE_TYPE: "file"
#      KMAGIC_CONFIG_STORE_CONNECTION: "Data Source=/config/KafkaMagicConfig.db;"
#      KMAGIC_CONFIG_ENCRYPTION_KEY: "ENTER_YOUR_KEY_HERE"
# =================================================